PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_S_ERDAT.

MODULE %_S_AUART.

MODULE %_S_KUNNR.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

FIELD !P_VKORG MODULE %_P_VKORG .

CHAIN.
  FIELD  S_ERDAT-LOW.
  FIELD  S_ERDAT-HIGH.
  MODULE %_S_ERDAT.
ENDCHAIN.

CHAIN.
  FIELD  S_AUART-LOW.
  FIELD  S_AUART-HIGH.
  MODULE %_S_AUART.
ENDCHAIN.

CHAIN.
  FIELD  S_KUNNR-LOW.
  FIELD  S_KUNNR-HIGH.
  MODULE %_S_KUNNR.
ENDCHAIN.

CHAIN.
  FIELD P_MODE_H.
  FIELD P_MODE_I.
    MODULE %_RADIOBUTTON_GROUP_G1                            .
ENDCHAIN.

FIELD !P_MAX MODULE %_P_MAX .

FIELD !P_DEMO MODULE %_P_DEMO .


CHAIN.
  FIELD P_VKORG .
  FIELD  S_ERDAT-LOW.
  FIELD  S_ERDAT-HIGH.
  FIELD  S_AUART-LOW.
  FIELD  S_AUART-HIGH.
  FIELD  S_KUNNR-LOW.
  FIELD  S_KUNNR-HIGH.
  FIELD P_MODE_H.
  FIELD P_MODE_I.
  FIELD P_MAX .
  FIELD P_DEMO .
    MODULE %_BLOCK_1000000.
ENDCHAIN.

CHAIN.
  FIELD P_VKORG .
  FIELD  S_ERDAT-LOW.
  FIELD  S_ERDAT-HIGH.
  FIELD  S_AUART-LOW.
  FIELD  S_AUART-HIGH.
  FIELD  S_KUNNR-LOW.
  FIELD  S_KUNNR-HIGH.
  FIELD P_MODE_H.
  FIELD P_MODE_I.
  FIELD P_MAX .
  FIELD P_DEMO .
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.